### ISSUE TITLE
Take `client_certificate` as file path in `owner_onboarding_server.yml`

### ISSUE THREAD

**Issue by nak3** [fedora-iot/fido-device-onboard-rs#466]
As current `client_certificate` expects `Vec<u8>`:

https://github.com/fedora-iot/fido-device-onboard-rs/blob/874b97e3236e6a3c9e57fd9ea5f4d177e3a80ab6/http-wrapper/src/client.rs#L56-L57

, we have to configure the `client_certificate` in `owner_onboarding_server.yml` with vector like:

```yaml
service_info_api_authentication:
  ClientCertificate:
    client_certificate: [0x01,0x02,0x03,0x04,0x05]
    password: "foo"
```

It is not practical. So`client_certificate` should take a file path (with `String`) and then change the program to read the cetificate from the file.
